# Laplacian

Suppose you have a graph 
$𝐺=(𝑉,𝐸)$ with:

$𝑛=∣𝑉∣$ nodes

An adjacency matrix 
$𝐴∈𝑅^{𝑛×𝑛}$, where 
$𝐴_{𝑖𝑗}$
 is the edge weight between nodes 
$𝑖$
 and 
$𝑗$
 (0 if no edge)

A degree matrix 
$𝐷$
, which is diagonal with entries 
$𝐷_{𝑖𝑖}=
∑_{𝑗}𝐴_{𝑖𝑗}$
 (the sum of edge weights connected to node 
$𝑖$
)

Then the unnormalized graph Laplacian is:

$𝐿=𝐷−𝐴$


In [107]:
# Let's build the graph

import numpy as np
V = np.array([0, 1, 2, 3]) # Nodes
E = np.array([[0, 1], [1, 2], [2, 3]]) # Edges: for example, (0, 1) means there's an edge between node 0 and node 1

A = np.zeros((len(V), len(V))) # Adjacency matrix
for edge in E:
    A[edge[0], edge[1]] = 1
    A[edge[1], edge[0]] = 1

# Here we get:
print("Adjacency Matrix:")
print(A)

D = np.diag(np.sum(A, axis=1)) # Degree matrix
print("Degree Matrix:")
print(D)

L = D - A # Unnormalized Laplacian
print("Unnormalized Laplacian:")
print(L)

Adjacency Matrix:
[[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]
Degree Matrix:
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 1.]]
Unnormalized Laplacian:
[[ 1. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  1.]]


### Why D - A?

1. **Degree Matrix (D)**: The degree matrix captures the total connection strength of each node. By placing these values on the diagonal, it provides a measure of how "connected" each node is within the graph.
2. **Adjacency Matrix (A)**: The adjacency matrix represents the actual connections between nodes. Each entry indicates whether a direct connection exists and, in weighted graphs, the strength of that connection.
3. **Laplacian Matrix (L = D - A)**: By subtracting the adjacency matrix from the degree matrix, we create a representation that highlights the structure of the graph. The Laplacian matrix has several important properties:
   - It is symmetric and positive semi-definite.
   - Its eigenvalues provide insights into the graph's connectivity and can be used for tasks like clustering and dimensionality reduction.


## Normalized Graph Laplacian

The normalized graph Laplacian is defined as:

$$
\mathcal{L} = D^{-1/2} L D^{-1/2} = I - D^{-1/2} A D^{-1/2}
$$

Where:
- $D^{-1/2}$ is the inverse square root of the degree matrix.
- $I$ is the identity matrix.

### Why Normalize?

1. **Scale Invariance**: Normalization ensures that the Laplacian is invariant to the scale of the graph. This is particularly important in applications like spectral clustering, where the absolute values of the eigenvalues can be influenced by the degree distribution of the graph.
2. **Improved Convergence**: In optimization problems, using the normalized Laplacian can lead to better convergence properties.
3. **Interpretability**: The normalized Laplacian can be interpreted in terms of random walks on the graph, providing insights into the flow of information.


In [6]:
# Normalized Laplacian

D_inv_sqrt = np.linalg.inv(np.sqrt(D)) # Inverse square root of degree matrix
L_normalized = D_inv_sqrt @ L @ D_inv_sqrt

print("Normalized Laplacian:")
print(L_normalized)

Normalized Laplacian:
[[ 1.         -0.70710678  0.          0.        ]
 [-0.70710678  1.         -0.5         0.        ]
 [ 0.         -0.5         1.         -0.70710678]
 [ 0.          0.         -0.70710678  1.        ]]


In [60]:
D

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 1.]])

In [61]:
det_D = np.linalg.det(D)
det_D

np.float64(4.0)